import { ReactNode } from 'react';
import localFont from "next/font/local";
import "./globals.css";
import LanguageSelector from "../components/LanguageSelector";
import { LanguageProvider } from "../i18n/LanguageContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <LanguageProvider>
          <header>
            <nav>
              <LanguageSelector />
            </nav>
          </header>
          {children}
        </LanguageProvider>
      </body>
    </html>
  );
}