name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.19.1'  

    - name: Install dependencies
      working-directory: ./nextjs_front-master
      run: npm install

    # - name: Run tests
    #   working-directory: ./nextjs_front-master
    #   run: npm test

    - name: Build application
      working-directory: ./nextjs_front-master
      run: npm run build  
